name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libgranite-dev libgtk-3-dev libjson-glib-dev libgee-0.8-dev libsoup2.4-dev libxml2-dev uuid-dev libhandy-1-dev meson valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  flatpak:
    runs-on: ubuntu-latest
    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle: "home.flatpak"
        manifest-path: "com.github.manexim.home.yml"
        run-tests: "true"

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: elementary/actions/vala-lint@master
